# Generated by Django 3.0.6 on 2020-05-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_auto_20200527_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='body',
            field=models.TextField(max_length=140),
        ),
    ]
