# Generated by Django 3.0.6 on 2020-05-28 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tweet', '0003_auto_20200527_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='tweet_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tweet_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
