# Generated by Django 3.0.6 on 2020-05-28 23:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitteruser', '0002_remove_myuser_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='following',
            field=models.ManyToManyField(related_name='_myuser_following_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
